# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06a65e0ff217dcf0b929ae85d04221641ad57ed85e479b00fd5630f4834c41da8e944e6bac0f84de6fed2efb24f59ba23ef777ca2f2384cede45144156db1480

test:
  secret_key_base: a11ae509738814768f5dddf21237c0bf5827ef0bce619145b2359c50b503f39dc0fab97f80324fe54f77d7c841d1f6541f0d961635bf02d432a98d997e006353

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
